"""Consolidated unit tests for src.src/setup/pipeline/orchestrator.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/pipeline/test_orchestrator_unit.py
 - tests/setup/pipeline/test_orchestrator_extra_unit.py
 - tests/setup/pipeline/test_orchestrator_variants.py
"""

from types import SimpleNamespace

from src.setup.pipeline import orchestrator


def test_set_tui_mode_and_restore():
    def r1(x):
        pass

    def r2(x):
        pass

    restore = orchestrator.set_tui_mode(r1, r2)
    assert orchestrator._TUI_MODE is True
    restore()
    assert orchestrator._TUI_MODE in (False, True)


def test_run_pipeline_step_choices(monkeypatch):
    # Simulate choosing 'y' and a failing run_program
    monkeypatch.setattr(orchestrator, "ask_text", lambda prompt, default="y": "y")
    monkeypatch.setattr(
        orchestrator, "run_program", lambda name, path, stream_output=False: False
    )
    ok = orchestrator._run_pipeline_step(
        "k", "program_1", SimpleNamespace(), "fail", "confirm"
    )
    assert ok is False

    # Simulate skip
    monkeypatch.setattr(orchestrator, "ask_text", lambda prompt, default="y": "s")
    ok2 = orchestrator._run_pipeline_step(
        "k", "program_1", SimpleNamespace(), "fail", "confirm", skip_message="skip_key"
    )
    assert ok2 is True


def test_run_pipeline_by_name(monkeypatch):
    monkeypatch.setattr(orchestrator, "run_markdown", lambda: True)
    monkeypatch.setattr(orchestrator, "ai_processor_main", lambda: None)
    monkeypatch.setattr(orchestrator, "run_website", lambda: True)
    assert orchestrator.run_pipeline_by_name("program_1") is True
    assert orchestrator.run_pipeline_by_name("program_2") is True
    assert orchestrator.run_pipeline_by_name("program_3") is True
