"""Consolidated unit tests for src.src/setup/pipeline/orchestrator.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/pipeline/test_orchestrator_unit.py
 - tests/setup/pipeline/test_orchestrator_extra_unit.py
 - tests/setup/pipeline/test_orchestrator_variants.py
"""


from types import SimpleNamespace
from src.setup.pipeline import orchestrator
import src.setup.pipeline.orchestrator as orch

### BEGIN ORIGINAL: tests/setup/pipeline/test_orchestrator_unit.py
def test_set_tui_mode_and_restore():
    def r1(x):
        pass

    def r2(x):
        pass

    restore = orchestrator.set_tui_mode(r1, r2)
    assert orchestrator._TUI_MODE is True
    restore()
    assert orchestrator._TUI_MODE in (False, True)


def test_run_pipeline_step_choices(monkeypatch):
    # Simulate choosing 'y' and a failing run_program
    monkeypatch.setattr(orchestrator, "ask_text", lambda prompt, default="y": "y")
    monkeypatch.setattr(orchestrator, "run_program", lambda name, path, stream_output=False: False)
    ok = orchestrator._run_pipeline_step("k", "program_1", SimpleNamespace(), "fail", "confirm")
    assert ok is False

    # Simulate skip
    monkeypatch.setattr(orchestrator, "ask_text", lambda prompt, default="y": "s")
    ok2 = orchestrator._run_pipeline_step("k", "program_1", SimpleNamespace(), "fail", "confirm", skip_message="skip_key")
    assert ok2 is True


def test_run_pipeline_by_name(monkeypatch):
    monkeypatch.setattr(orchestrator, "run_markdown", lambda: True)
    monkeypatch.setattr(orchestrator, "ai_processor_main", lambda: None)
    monkeypatch.setattr(orchestrator, "run_website", lambda: True)
    assert orchestrator.run_pipeline_by_name("program_1") is True
    assert orchestrator.run_pipeline_by_name("program_2") is True
    assert orchestrator.run_pipeline_by_name("program_3") is True
### END ORIGINAL: tests/setup/pipeline/test_orchestrator_unit.py
### BEGIN ORIGINAL: tests/setup/pipeline/test_orchestrator_extra_unit.py
def test_compose_and_update_group_fallback(monkeypatch):
    """When both status and progress renderables exist a Group is composed."""
    captured = {}

    def updater(obj):
        captured["obj"] = obj

    monkeypatch.setattr(orch, "_TUI_MODE", True)
    monkeypatch.setattr(orch, "_TUI_UPDATER", updater)
    monkeypatch.setattr(orch, "_STATUS_RENDERABLE", "S")
    monkeypatch.setattr(orch, "_PROGRESS_RENDERABLE", "P")

    orch._compose_and_update()
    assert "obj" in captured
    # Fallback Group exposes .items containing the two renderables
    assert hasattr(captured["obj"], "items") and captured["obj"].items == ("S", "P")
### END ORIGINAL: tests/setup/pipeline/test_orchestrator_extra_unit.py
### BEGIN ORIGINAL: tests/setup/pipeline/test_orchestrator_variants.py
def test_compose_and_update_no_render(monkeypatch):
    # Ensure when TUI disabled nothing happens
    monkeypatch.setattr(orchestrator, "_TUI_MODE", False)
    monkeypatch.setattr(orchestrator, "_TUI_UPDATER", None)
    # Should not raise
    orchestrator._compose_and_update()


def test_run_pipeline_by_name_unknown(monkeypatch):
    # Unknown program uses run_program fallback
    called = {}
    monkeypatch.setattr(orchestrator, "run_program", lambda name, path, stream_output=False: (called.setdefault("ok", True)))
    res = orchestrator.run_pipeline_by_name("unknown_prog")
    assert called.get("ok") is True or res is False


def test_run_processing_pipeline_plain_early_exit(monkeypatch):
    # If ai_check declines, pipeline exits early
    monkeypatch.setattr(orchestrator, "ask_confirm", lambda *a, **k: False)
    # Should simply return without exception
    orchestrator._run_processing_pipeline_plain()


def test_run_processing_pipeline_plain_program1_fail(monkeypatch):
    monkeypatch.setattr(orchestrator, "ask_confirm", lambda *a, **k: True)
    monkeypatch.setattr(orchestrator, "run_ai_connectivity_check_interactive", lambda: True)
    monkeypatch.setattr(orchestrator, "_run_pipeline_step", lambda *a, **k: False)
    # Should return early without raising
    orchestrator._run_processing_pipeline_plain()
### END ORIGINAL: tests/setup/pipeline/test_orchestrator_variants.py
