"""Consolidated unit tests for src.src/setup/pipeline/orchestrator.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/pipeline/test_orchestrator_unit.py
 - tests/setup/pipeline/test_orchestrator_extra_unit.py
 - tests/setup/pipeline/test_orchestrator_variants.py
"""

from src.setup.pipeline import orchestrator


def test_compose_and_update_no_render(monkeypatch):
    # Ensure when TUI disabled nothing happens
    monkeypatch.setattr(orchestrator, "_TUI_MODE", False)
    monkeypatch.setattr(orchestrator, "_TUI_UPDATER", None)
    # Should not raise
    orchestrator._compose_and_update()


def test_run_pipeline_by_name_unknown(monkeypatch):
    # Unknown program uses run_program fallback
    called = {}
    monkeypatch.setattr(
        orchestrator,
        "run_program",
        lambda name, path, stream_output=False: (called.setdefault("ok", True)),
    )
    res = orchestrator.run_pipeline_by_name("unknown_prog")
    assert called.get("ok") is True or res is False


def test_run_processing_pipeline_plain_early_exit(monkeypatch):
    # If ai_check declines, pipeline exits early
    monkeypatch.setattr(orchestrator, "ask_confirm", lambda *a, **k: False)
    # Should simply return without exception
    orchestrator._run_processing_pipeline_plain()


def test_run_processing_pipeline_plain_program1_fail(monkeypatch):
    monkeypatch.setattr(orchestrator, "ask_confirm", lambda *a, **k: True)
    monkeypatch.setattr(
        orchestrator, "run_ai_connectivity_check_interactive", lambda: True
    )
    monkeypatch.setattr(orchestrator, "_run_pipeline_step", lambda *a, **k: False)
    # Should return early without raising
    orchestrator._run_processing_pipeline_plain()
