"""Consolidated unit tests for src.src/setup/pipeline/orchestrator.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/pipeline/test_orchestrator_unit.py
 - tests/setup/pipeline/test_orchestrator_extra_unit.py
 - tests/setup/pipeline/test_orchestrator_variants.py
"""

import src.setup.pipeline.orchestrator as orch


def test_compose_and_update_group_fallback(monkeypatch):
    """When both status and progress renderables exist a Group is composed."""
    captured = {}

    def updater(obj):
        captured["obj"] = obj

    monkeypatch.setattr(orch, "_TUI_MODE", True)
    monkeypatch.setattr(orch, "_TUI_UPDATER", updater)
    monkeypatch.setattr(orch, "_STATUS_RENDERABLE", "S")
    monkeypatch.setattr(orch, "_PROGRESS_RENDERABLE", "P")

    orch._compose_and_update()
    assert "obj" in captured
    # Fallback Group exposes .items containing the two renderables
    assert hasattr(captured["obj"], "items") and captured["obj"].items == ("S", "P")
