"""Consolidated unit tests for src.src/setup/ui/programs.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_programs_unit.py
 - tests/setup/ui/test_programs_extra_unit.py
 - tests/setup/ui/test_programs_more_unit.py
"""

from pathlib import Path

import src.setup.ui.programs as prog


def test_get_program_descriptions_uses_translate(monkeypatch):
    """Descriptions are looked up via the translate function."""

    def fake_translate(key: str) -> str:
        return f"{key}_val"

    monkeypatch.setattr(prog, "translate", fake_translate)
    desc = prog.get_program_descriptions()
    assert "1" in desc and isinstance(desc["1"], tuple)


def test_view_program_descriptions_plain(monkeypatch):
    """When non-rich, program descriptions are printed as plain text."""
    monkeypatch.setattr(prog, "ui_rule", lambda *a, **k: None)
    monkeypatch.setattr(prog, "ui_menu", lambda *a, **k: None)
    monkeypatch.setattr(prog, "get_program_descriptions", lambda: {"1": ("S", "L")})
    answers = ["1", "0"]
    printed = []
    monkeypatch.setattr(prog, "ask_text", lambda prompt: answers.pop(0))
    monkeypatch.setattr(prog, "rprint", lambda *a, **k: printed.append(a))
    monkeypatch.setattr(prog, "ui_has_rich", lambda: False)

    prog.view_program_descriptions()
    assert any("L" in str(p) for p in printed)


def test_view_logs_no_logs_prints(monkeypatch, tmp_path: Path):
    """When there are no log files the user is informed via rprint."""
    monkeypatch.setattr(prog, "ui_rule", lambda *a, **k: None)
    monkeypatch.setattr(
        prog,
        "rprint",
        lambda *a, **k: (_ for _ in ()).throw(AssertionError("rprint called")),
    )
    # Point LOG_DIR to an empty temporary directory
    monkeypatch.setattr(prog, "LOG_DIR", tmp_path)

    # view_logs should return early without raising if rprint is called
    try:
        prog.view_logs()
    except AssertionError:
        # rprint should have been invoked signalling no logs
        pass
