"""Consolidated unit tests for src.src/setup/ui/menu.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_menu_unit.py
 - tests/setup/ui/test_menu_extra_unit.py
"""

import src.setup.ui.menu as menu


def test_ui_items_handles_colon_and_space_variants(monkeypatch):
    """Menu labels are trimmed correctly whether they contain ": " or not."""

    def fake_translate(key: str) -> str:
        # Return different patterns for the first and second key
        if key.endswith("1"):
            return "1: OptionOne"
        return "Menu OptionTwo"

    monkeypatch.setattr(menu, "translate", fake_translate)
    items = menu._ui_items()
    assert items[0][1] == "OptionOne"
    assert items[1][1] == "OptionTwo"


def test_main_menu_plain_invalid_choice_prints(monkeypatch):
    """An invalid selection should trigger `invalid_choice` output."""
    seq = ["x", "6"]
    printed = []

    monkeypatch.setattr(menu, "ask_text", lambda prompt: seq.pop(0))
    monkeypatch.setattr(menu, "_manage_env", lambda: None)
    monkeypatch.setattr(menu, "view_program_descriptions", lambda: None)
    monkeypatch.setattr(menu, "run_processing_pipeline", lambda *a, **k: None)
    monkeypatch.setattr(menu, "view_logs", lambda: None)
    monkeypatch.setattr(menu, "reset_project", lambda: None)
    monkeypatch.setattr(menu, "rprint", lambda *a, **k: printed.append(a))

    menu._main_menu_plain()
    # The invalid choice should have resulted in a printed message
    assert any(
        "invalid_choice" in str(x) or isinstance(x, str) for tup in printed for x in tup
    )
