"""Consolidated unit tests for src.src/setup/ui/prompts.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_prompts_unit.py
 - tests/setup/ui/test_prompts_extra_unit.py
"""

import builtins
import sys
from types import SimpleNamespace

import src.setup.ui.prompts as prom


def test_ask_confirm_with_questionary(monkeypatch):
    """When questionary is available the confirm adapter should be used."""

    class Q:
        @staticmethod
        def confirm(prompt, default=True):
            return SimpleNamespace(ask=lambda: True)

    import importlib

    pkg = importlib.import_module("src.setup.pipeline")
    stub = SimpleNamespace(_TUI_MODE=False, _TUI_UPDATER=None)
    monkeypatch.setattr(pkg, "orchestrator", stub, raising=False)
    monkeypatch.setitem(sys.modules, "src.setup.pipeline.orchestrator", stub)
    monkeypatch.setattr(prom.ch, "_HAS_Q", True)
    monkeypatch.setattr(prom.ch, "questionary", Q)
    assert prom.ask_confirm("?") is True


def test_ask_select_fallback_on_eof(monkeypatch):
    """ask_select should return the last choice when input fails."""
    monkeypatch.setattr(prom.ch, "_HAS_Q", False)
    monkeypatch.setattr(prom.ch, "questionary", None)
    monkeypatch.setattr(
        builtins, "input", lambda prompt="": (_ for _ in ()).throw(EOFError())
    )
    choices = ["A", "B"]
    assert prom.ask_select("x", choices) == "B"
