"""Consolidated unit tests for src.src/setup/ui/programs.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_programs_unit.py
 - tests/setup/ui/test_programs_extra_unit.py
 - tests/setup/ui/test_programs_more_unit.py
"""

from pathlib import Path

from src.setup.ui import programs


def test_get_program_descriptions_has_three():
    desc = programs.get_program_descriptions()
    assert set(desc.keys()) == {"1", "2", "3"}


def test_view_program_descriptions_plain(monkeypatch):
    # Simulate choosing program 1 then returning
    seq = ["1", "0"]
    monkeypatch.setattr(programs, "ask_text", lambda prompt: seq.pop(0))
    monkeypatch.setattr(programs, "ui_menu", lambda items: None)
    monkeypatch.setattr(programs, "ui_rule", lambda arg: None)
    monkeypatch.setattr(programs, "ui_has_rich", lambda: False)
    programs.view_program_descriptions()


def test__view_program_descriptions_tui(monkeypatch):
    captured = {}

    def update_right(obj):
        captured["last"] = obj

    monkeypatch.setattr(programs, "ask_text", lambda prompt: "1")
    programs._view_program_descriptions_tui(update_right, lambda p: None)
    assert "last" in captured


def test__view_logs_tui_no_logs(monkeypatch, tmp_path: Path):
    monkeypatch.setattr(programs, "LOG_DIR", tmp_path)
    captured = {}

    def update_right(obj):
        captured["last"] = obj

    programs._view_logs_tui(update_right, lambda p: None)
    assert "last" in captured


def test_view_logs_with_files(monkeypatch, tmp_path: Path):
    monkeypatch.setattr(programs, "LOG_DIR", tmp_path)
    f = tmp_path / "a.log"
    f.write_text("hello")
    seq = ["1", "0"]
    monkeypatch.setattr(programs, "ask_text", lambda prompt: seq.pop(0))
    monkeypatch.setattr(programs, "ui_menu", lambda items: None)
    monkeypatch.setattr(programs, "ui_rule", lambda arg: None)
    monkeypatch.setattr(programs, "ui_has_rich", lambda: False)

    programs.view_logs()
