"""Consolidated unit tests for src.src/setup/ui/programs.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_programs_unit.py
 - tests/setup/ui/test_programs_extra_unit.py
 - tests/setup/ui/test_programs_more_unit.py
"""

from pathlib import Path

from src.setup.ui import programs


def test_view_program_descriptions_invalid_then_exit(monkeypatch):
    seq = ["9", "0"]
    monkeypatch.setattr(programs, "ask_text", lambda prompt: seq.pop(0))
    monkeypatch.setattr(programs, "ui_menu", lambda items: None)
    monkeypatch.setattr(programs, "ui_rule", lambda arg: None)
    monkeypatch.setattr(programs, "ui_has_rich", lambda: False)
    programs.view_program_descriptions()


def test__view_logs_tui_select_by_name(monkeypatch, tmp_path: Path):
    # Prepare log files
    d = tmp_path
    (d / "alpha.log").write_text("one")
    (d / "beta.log").write_text("two")
    monkeypatch.setattr(programs, "LOG_DIR", d)
    # First call selects by literal name, then 0 to exit
    seq = ["alpha.log", "0"]
    monkeypatch.setattr(programs, "ask_text", lambda prompt: seq.pop(0))

    captured = {}

    def update_right(obj):
        captured.setdefault("last", obj)

    programs._view_logs_tui(update_right, lambda p: None)
    assert "last" in captured
