"""Consolidated unit tests for src.src/setup/ui/menu.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/ui/test_menu_unit.py
 - tests/setup/ui/test_menu_extra_unit.py
"""

import src.setup.ui.menu as menu


def test_ui_items_has_six_items():
    items = menu._ui_items()
    assert len(items) == 6


def test_manage_env_calls_manager(monkeypatch):
    called = {}

    def fake_manage(*a, **k):
        called["ok"] = True

    monkeypatch.setattr(menu, "manage_virtual_environment", fake_manage)
    menu._manage_env()
    assert called.get("ok") is True


def test_main_menu_plain_exits_quickly(monkeypatch):
    # Provide a sequence of answers: choose '2' then '6' to exit.
    seq = ["2", "6"]

    def ask(_):
        return seq.pop(0)

    monkeypatch.setattr(menu, "ask_text", lambda prompt: ask(prompt))
    # Patch heavy functions to no-op
    monkeypatch.setattr(menu, "_manage_env", lambda: None)
    monkeypatch.setattr(menu, "view_program_descriptions", lambda: None)
    monkeypatch.setattr(menu, "run_processing_pipeline", lambda *a, **k: None)
    monkeypatch.setattr(menu, "view_logs", lambda: None)
    monkeypatch.setattr(menu, "reset_project", lambda: None)

    menu._main_menu_plain()


def test_main_menu_rich_dashboard_quick_exit(monkeypatch):
    monkeypatch.setattr(menu, "ask_text", lambda prompt: "6")
    monkeypatch.setattr(menu, "_manage_env", lambda: None)
    monkeypatch.setattr(menu, "view_program_descriptions", lambda: None)
    monkeypatch.setattr(menu, "run_processing_pipeline", lambda *a, **k: None)
    monkeypatch.setattr(menu, "view_logs", lambda: None)
    monkeypatch.setattr(menu, "reset_project", lambda: None)

    # Call the rich dashboard variant directly
    menu._main_menu_rich_dashboard()
