name: Harden Runner (composite action)
description: |
  Composite action wrapper around the external `step-security/harden-runner`
  action with a small optional preflight verification step. Use this action
  from job steps to consistently apply the hardened egress policy.

inputs:
  egress-policy:
    description: Egress policy to pass to the underlying harden-runner action.
    required: false
    default: 'block'
  allowed-endpoints:
    description: |
      Multi-line list of allowed host:port endpoints (newline-separated).
      The default list mirrors the project's previous configuration and
      includes GitHub, PyPI, Codecov, OSV and other required hosts.
    required: false
    default: |
      github.com:443
      codeload.github.com:443
      api.github.com:443
      raw.githubusercontent.com:443
      objects.githubusercontent.com:443
      uploads.github.com:443
      results-receiver.actions.githubusercontent.com:443
      actions-results-receiver-production.githubapp.com:443
      pypi.org:443
      files.pythonhosted.org:443
      pypi.python.org:443
      pip.pypa.io:443
      storage.googleapis.com:443
      codecov.io:443
      api.codecov.io:443
      uploader.codecov.io:443
      uploads.codecov.io:443
      static.codecov.io:443
      ghcr.io:443
      pkg-containers.githubusercontent.com:443
      registry.semgrep.dev:443
      semgrep.dev:443
      osv.dev:443
      api.osv.dev:443
      productionresultssa12.blob.core.windows.net:443
      productionresultssa9.blob.core.windows.net:443
      agent.api.stepsecurity.io:443
  verify-preflight:
    description: Whether to run the local preflight verification script.
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Harden Runner
      id: harden
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
      with:
        egress-policy: ${{ inputs.egress-policy }}
        allowed-endpoints: ${{ inputs.allowed-endpoints }}

    - name: Verify Harden Runner (preflight)
      if: ${{ inputs.verify-preflight == 'true' }}
      shell: bash
      run: |
        # Lightweight preflight check to ensure the hardened runner blocks
        # unexpected egress. The verification script is intentionally
        # conservative and retries a few times to account for transient CI
        # runner scheduling delays.
        bash tools/ci/verify_harden_runner.sh --tries 3 --timeout 8
