# Composite action to apply the hardened runner policy and run a preflight check.
#
# This composite action centralizes the invocation of the external
# `step-security/harden-runner` action and the local preflight verification
# script (`tools/ci/verify_harden_runner.sh`). It accepts an override for the
# `allowed-endpoints` list and the egress policy, but provides a sensible
# default union of endpoints used across the workflow.

name: Harden Runner (composite)
description: "Apply runner hardening and (optionally) run a preflight verify."
inputs:
  egress-policy:
    description: 'Egress policy to apply.'
    required: false
    default: 'block'
  allowed-endpoints:
    description: 'Newline-separated allowed endpoints. If omitted a default union is used.'
    required: false
    default: |
      github.com:443
      codeload.github.com:443
      api.github.com:443
      raw.githubusercontent.com:443
      objects.githubusercontent.com:443
      uploads.github.com:443
      results-receiver.actions.githubusercontent.com:443
      actions-results-receiver-production.githubapp.com:443
      pypi.org:443
      files.pythonhosted.org:443
      pypi.python.org:443
      pip.pypa.io:443
      storage.googleapis.com:443
      codecov.io:443
      api.codecov.io:443
      uploader.codecov.io:443
      uploads.codecov.io:443
      static.codecov.io:443
      ghcr.io:443
      pkg-containers.githubusercontent.com:443
      registry.semgrep.dev:443
      semgrep.dev:443
      osv.dev:443
      api.osv.dev:443
      productionresultssa12.blob.core.windows.net:443
      productionresultssa9.blob.core.windows.net:443
      agent.api.stepsecurity.io:443
  verify-preflight:
    description: 'Run the verify_harden_runner.sh preflight check?'
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a
      with:
        egress-policy: ${{ inputs.egress-policy }}
        allowed-endpoints: ${{ inputs.allowed-endpoints }}

    - name: Verify Harden Runner (preflight)
      if: ${{ inputs.verify-preflight == 'true' && runner.os != 'Windows' }}
      continue-on-error: true
      shell: bash
      run: bash tools/ci/verify_harden_runner.sh --tries 3 --timeout 8
