"""Consolidated unit tests for src.src/pipeline/website_generator/runner.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/website_generator/test_runner_extra_unit.py
 - tests/pipeline/website_generator/test_runner_web_unit.py
"""

from pathlib import Path

import src.pipeline.website_generator.runner as runner


def test_run_from_config_no_data(monkeypatch, tmp_path: Path):
    out = tmp_path / "out.html"
    monkeypatch.setattr(runner, "load_school_data", lambda csv, md: [])
    monkeypatch.setattr(
        runner, "write_html_output", lambda html, path: path.write_text(html)
    )
    ok = runner.run_from_config(
        csv_path=tmp_path / "no.csv", ai_markdown_dir=tmp_path, output_file=out
    )
    assert ok is True
    assert out.exists()


def test_run_from_config_with_data(monkeypatch, tmp_path: Path):
    out = tmp_path / "out2.html"
    monkeypatch.setattr(runner, "load_school_data", lambda csv, md: [{"a": 1}])
    monkeypatch.setattr(
        runner, "generate_final_html", lambda schools, tpl: "<html>ok</html>"
    )
    monkeypatch.setattr(
        runner, "write_html_output", lambda html, path: path.write_text(html)
    )
    ok = runner.run_from_config(
        csv_path=tmp_path / "ok.csv", ai_markdown_dir=tmp_path, output_file=out
    )
    assert ok is True
    assert out.read_text() == "<html>ok</html>"
