"""Consolidated unit tests for src.src/pipeline/website_generator/runner.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/website_generator/test_runner_extra_unit.py
 - tests/pipeline/website_generator/test_runner_web_unit.py
"""


from types import SimpleNamespace
from pathlib import Path
import src.pipeline.website_generator.runner as runner
from src.pipeline.website_generator import runner

### BEGIN ORIGINAL: tests/pipeline/website_generator/test_runner_extra_unit.py
def test_run_from_config_writes_no_data(monkeypatch, tmp_path: Path):
    """If loader returns empty list a 'no data' page is written."""
    monkeypatch.setattr(runner, "load_school_data", lambda csv, md: [])
    called = {}

    def fake_write(html, out):
        called["ok"] = True

    monkeypatch.setattr(runner, "write_html_output", fake_write)
    ok = runner.run_from_config(csv_path=tmp_path / "s.csv", ai_markdown_dir=tmp_path, output_file=tmp_path / "out.html")
    assert ok is True and called.get("ok")


def test_run_from_config_loader_exception_returns_false(monkeypatch, tmp_path: Path):
    """Loader exceptions should be caught and reported as False."""
    def bad_loader(*a, **k):
        raise RuntimeError("boom")

    monkeypatch.setattr(runner, "load_school_data", bad_loader)
    ok = runner.run_from_config(csv_path=tmp_path / "s.csv", ai_markdown_dir=tmp_path, output_file=tmp_path / "out.html")
    assert ok is False
### END ORIGINAL: tests/pipeline/website_generator/test_runner_extra_unit.py
### BEGIN ORIGINAL: tests/pipeline/website_generator/test_runner_web_unit.py
def test_run_from_config_no_data(monkeypatch, tmp_path: Path):
    out = tmp_path / "out.html"
    monkeypatch.setattr(runner, "load_school_data", lambda csv, md: [])
    monkeypatch.setattr(runner, "write_html_output", lambda html, path: path.write_text(html))
    ok = runner.run_from_config(csv_path=tmp_path / "no.csv", ai_markdown_dir=tmp_path, output_file=out)
    assert ok is True
    assert out.exists()


def test_run_from_config_with_data(monkeypatch, tmp_path: Path):
    out = tmp_path / "out2.html"
    monkeypatch.setattr(runner, "load_school_data", lambda csv, md: [{"a": 1}])
    monkeypatch.setattr(runner, "generate_final_html", lambda schools, tpl: "<html>ok</html>")
    monkeypatch.setattr(runner, "write_html_output", lambda html, path: path.write_text(html))
    ok = runner.run_from_config(csv_path=tmp_path / "ok.csv", ai_markdown_dir=tmp_path, output_file=out)
    assert ok is True
    assert out.read_text() == "<html>ok</html>"
### END ORIGINAL: tests/pipeline/website_generator/test_runner_web_unit.py

