"""Consolidated unit tests for src.src/pipeline/markdown_generator/runner.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/markdown_generator/test_runner_unit.py
 - tests/program1/test_cli.py
"""

import src.pipeline.markdown_generator.runner as p1


def test_configure_logging_filehandler_error(monkeypatch):
    """Test Configure logging filehandler error."""

    class BadFH:
        """Test BadFH."""

        def __init__(self, *a, **k):
            """Test Init."""
            raise RuntimeError("fh error")

    monkeypatch.setattr(p1.logging, "FileHandler", BadFH)
    p1.configure_logging("INFO", enable_file=True)
