"""Consolidated unit tests for src.src/pipeline/ai_processor/client.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/ai_processor/test_client_unit.py
 - tests/pipeline/ai_processor/test_client_extra2_unit.py
 - tests/pipeline/ai_processor/test_client_extra_unit.py
 - tests/pipeline/ai_processor/test_client_more_unit.py
"""

from types import SimpleNamespace

import pytest

from src.pipeline.ai_processor.client import AIAPIClient


class Resp:
    def __init__(self, status, text):
        self.status = status
        self._text = text

    async def text(self):
        return self._text

    async def __aenter__(self):
        return self

    async def __aexit__(self, *a):
        return False


class Sess:
    def __init__(self, resp):
        self.resp = resp

    def post(self, *a, **k):
        return self.resp


@pytest.mark.asyncio
async def test_http_500_then_fail_no_retry():
    cfg = SimpleNamespace(
        api_key="k", gpt4o_endpoint="http://x", max_retries=0, backoff_factor=0
    )
    client = AIAPIClient(cfg)
    payload = {}
    session = Sess(Resp(500, "err body"))
    ok, content, data = await client.process_content(session, payload)
    assert ok is False
    assert data.get("status_code") == 500 or data.get("error_body") == "err body"


@pytest.mark.asyncio
async def test_timeout_error_branch():
    cfg = SimpleNamespace(
        api_key="k", gpt4o_endpoint="http://x", max_retries=0, backoff_factor=0
    )
    client = AIAPIClient(cfg)

    class BadSess:
        def post(self, *a, **k):
            raise TimeoutError()

    ok, content, data = await client.process_content(BadSess(), {})
    assert ok is False
    assert data.get("error_type") in ("TimeoutError", "Exception")
