"""Consolidated unit tests for src.src/pipeline/ai_processor/client.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/ai_processor/test_client_unit.py
 - tests/pipeline/ai_processor/test_client_extra2_unit.py
 - tests/pipeline/ai_processor/test_client_extra_unit.py
 - tests/pipeline/ai_processor/test_client_more_unit.py
"""

import json
from types import SimpleNamespace

import pytest

from src.pipeline.ai_processor.client import AIAPIClient


class SeqResponse:
    def __init__(self, session):
        self._session = session

    async def __aenter__(self):
        status, text = self._session.seq.pop(0)
        self.status = status
        self._text = text

        async def textfn():
            return self._text

        self.text = textfn
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return False


class SeqSession:
    def __init__(self, seq):
        # operate on a mutable list so SeqResponse instances consume it
        self.seq = list(seq)

    def post(self, *a, **k):
        return SeqResponse(self)


@pytest.mark.asyncio
async def test_429_then_success_retry():
    cfg = SimpleNamespace(
        api_key="k",
        gpt4o_endpoint="http://x",
        max_retries=1,
        backoff_factor=0,
        retry_sleep_on_429=0,
    )
    client = AIAPIClient(cfg)
    # First response 429, then a successful 200 with valid content
    good = {"choices": [{"message": {"content": "OK"}}]}
    seq = [(429, "rate"), (200, json.dumps(good))]
    session = SeqSession(seq)
    ok, content, data = await client.process_content(session, {})
    assert ok is True
    assert content == "OK"


@pytest.mark.asyncio
async def test_choices_not_list_returns_data():
    cfg = SimpleNamespace(api_key="k", gpt4o_endpoint="http://x", max_retries=0)
    client = AIAPIClient(cfg)
    payload = {"choices": "bad"}
    session = SeqSession([(200, json.dumps(payload))])
    ok, content, data = await client.process_content(session, {})
    assert ok is False
    assert isinstance(data, dict)
