"""Consolidated unit tests for src.src/setup/fs_utils.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/test_fs_utils_unit.py
 - tests/setup/test_setup_project_run_and_venv_unit.py
"""

import subprocess
from pathlib import Path
from types import SimpleNamespace

import setup_project as sp
from src.setup import fs_utils


def test_setup_project_run_program_non_stream(monkeypatch):
    monkeypatch.setattr(sp, "get_python_executable", lambda: "/usr/bin/python")

    class R:
        returncode = 0
        stdout = ""
        stderr = ""

    monkeypatch.setattr(subprocess, "run", lambda *a, **k: R())
    ok = sp.run_program(
        "program_1", Path("src/program1_generate_markdowns.py"), stream_output=False
    )
    assert ok is True


def test_manage_virtual_environment_recreate(monkeypatch, tmp_path: Path):
    # Simulate an existing venv and user confirming recreate
    monkeypatch.setattr(sp, "is_venv_active", lambda: False)
    monkeypatch.setattr(sp, "VENV_DIR", tmp_path / "venv")
    (sp.VENV_DIR).mkdir()
    seq = iter(["y", "y"])  # yes to manage, yes to recreate
    monkeypatch.setattr(sp, "ask_text", lambda prompt, default="y": next(seq))

    # Patch filesystem helpers and subprocess/venv calls

    monkeypatch.setattr(fs_utils, "create_safe_path", lambda p: p, raising=False)
    monkeypatch.setattr(fs_utils, "safe_rmtree", lambda p: None, raising=False)
    monkeypatch.setattr(
        sp, "get_venv_pip_executable", lambda p: p / "bin" / "pip", raising=False
    )
    monkeypatch.setattr(
        sp, "get_venv_python_executable", lambda p: p / "bin" / "python", raising=False
    )
    monkeypatch.setattr(
        sp, "venv", SimpleNamespace(create=lambda *a, **k: None), raising=False
    )
    monkeypatch.setattr(subprocess, "check_call", lambda *a, **k: None)

    # Should not raise
    sp.manage_virtual_environment()
