"""Consolidated unit tests for src.src/setup/fs_utils.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/test_fs_utils_unit.py
 - tests/setup/test_setup_project_run_and_venv_unit.py
"""

from pathlib import Path

import pytest

from src import config as _config
from src.setup import fs_utils


def test_create_safe_path_denies_project_root():
    with pytest.raises(PermissionError):
        fs_utils.create_safe_path(_config.PROJECT_ROOT)


def test_create_safe_path_outside(tmp_path: Path):
    # tmp_path is outside the project root and should be rejected
    with pytest.raises(PermissionError):
        fs_utils.create_safe_path(tmp_path)


def test_create_safe_path_and_safe_rmtree(tmp_path: Path, monkeypatch):
    # Create a directory under the whitelisted 'output' root and remove it
    out_root = _config.PROJECT_ROOT / "output"
    test_dir = out_root / "testsafe"
    test_dir.mkdir(parents=True, exist_ok=True)
    (test_dir / "f.txt").write_text("x")

    validated = fs_utils.create_safe_path(test_dir)
    assert isinstance(validated, Path)

    # Now remove it using safe_rmtree
    fs_utils.safe_rmtree(validated)
    assert not test_dir.exists()
