"""Consolidated unit tests for src.src/setup/fs_utils.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/setup/test_fs_utils_unit.py
 - tests/setup/test_setup_project_run_and_venv_unit.py
"""

import subprocess
from pathlib import Path
from types import SimpleNamespace

import setup_project as sp
from src.setup import fs_utils
from src import config as cfg


def test_setup_project_run_program_non_stream(monkeypatch):
    monkeypatch.setattr(sp, "get_python_executable", lambda: "/usr/bin/python")

    class R:
        returncode = 0
        stdout = ""
        stderr = ""

    monkeypatch.setattr(subprocess, "run", lambda *a, **k: R())
    ok = sp.run_program(
        "program_1", Path("src/program1_generate_markdowns.py"), stream_output=False
    )
    assert ok is True


def test_manage_virtual_environment_recreate(monkeypatch, tmp_path: Path):
    """Simulate an existing venv and user confirming recreate.

    This test verifies the manager's recreate branch. It patches the
    concrete configuration value ``src.config.VENV_DIR`` so that the
    operation targets a temporary directory instead of the repository
    venv. Filesystem helpers and subprocess invocations are stubbed so
    the test is side-effect free.

    Parameters
    ----------
    monkeypatch : _pytest.monkeypatch.MonkeyPatch
        Fixture to patch attributes and modules during the test.
    tmp_path : pathlib.Path
        Temporary path used to host a fake venv directory.

    Returns
    -------
    None
        The test asserts that no exception is raised and returns nothing.
    """
    # Simulate existing interpreter not active and ensure venv dir under cfg
    monkeypatch.setattr(sp, "is_venv_active", lambda: False)
    monkeypatch.setattr(cfg, "VENV_DIR", tmp_path / "venv", raising=True)
    (cfg.VENV_DIR).mkdir()
    # Return yes for prompts in this test (stable across orderings)
    monkeypatch.setattr(sp, "ask_text", lambda prompt, default="y": "y")

    # Patch filesystem helpers and subprocess/venv calls

    monkeypatch.setattr(fs_utils, "create_safe_path", lambda p: p, raising=False)
    monkeypatch.setattr(fs_utils, "safe_rmtree", lambda p: None, raising=False)
    monkeypatch.setattr(
        sp, "get_venv_pip_executable", lambda p: p / "bin" / "pip", raising=False
    )
    monkeypatch.setattr(
        sp, "get_venv_python_executable", lambda p: p / "bin" / "python", raising=False
    )
    monkeypatch.setattr(
        sp, "venv", SimpleNamespace(create=lambda *a, **k: None), raising=False
    )
    monkeypatch.setattr(subprocess, "check_call", lambda *a, **k: None)

    # Should not raise
    sp.manage_virtual_environment()
