"""Consolidated unit tests for src.src/pipeline/markdown_generator/runner.py

This file was autogenerated by a repository consolidation script.
Original test files:
 - tests/pipeline/markdown_generator/test_runner_unit.py
 - tests/program1/test_cli.py
"""


import logging
from types import SimpleNamespace
from src.pipeline.markdown_generator import runner
import src.pipeline.markdown_generator.runner as p1

### BEGIN ORIGINAL: tests/pipeline/markdown_generator/test_runner_unit.py
def test_configure_logging_swallow(monkeypatch, tmp_path):
    # Make FileHandler raise to ensure configure_logging swallows it
    monkeypatch.setattr(logging, "FileHandler", lambda *a, **k: (_ for _ in ()).throw(RuntimeError("boom")))
    runner.configure_logging(enable_file=True)


def test_run_from_config_success(monkeypatch):
    monkeypatch.setattr(runner, "load_template_and_placeholders", lambda p: ("tpl", {}))
    monkeypatch.setattr(runner, "process_csv_and_generate_markdowns", lambda c, t, ph, out: 3)
    ok = runner.run_from_config(csv_path=__import__('pathlib').Path('.'), template_path=__import__('pathlib').Path('.'), output_dir=__import__('pathlib').Path('.'))
    assert ok is True


def test_run_from_config_failure(monkeypatch):
    monkeypatch.setattr(runner, "load_template_and_placeholders", lambda p: (_ for _ in ()).throw(RuntimeError("bad")))
    ok = runner.run_from_config()
    assert ok is False
### END ORIGINAL: tests/pipeline/markdown_generator/test_runner_unit.py
### BEGIN ORIGINAL: tests/program1/test_cli.py
def test_configure_logging_filehandler_error(monkeypatch):
    """Test Configure logging filehandler error."""

    class BadFH:
        """Test BadFH."""

        def __init__(self, *a, **k):
            """Test Init."""
            raise RuntimeError("fh error")

    monkeypatch.setattr(p1.logging, "FileHandler", BadFH)
    p1.configure_logging("INFO", enable_file=True)
### END ORIGINAL: tests/program1/test_cli.py
